// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMrldiVaZxBfk6zhkpx41KizVEKzjsgSY',
    appId: '1:1043694505574:web:aeb2f4cf9b3a59208627a7',
    messagingSenderId: '1043694505574',
    projectId: 'flutterfire-ui-codelab-851e7',
    authDomain: 'flutterfire-ui-codelab-851e7.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-851e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrfwj6zwMjZRwvQLFAvpodQxuuDrPtk0M',
    appId: '1:1043694505574:android:a63f61542a8f631e8627a7',
    messagingSenderId: '1043694505574',
    projectId: 'flutterfire-ui-codelab-851e7',
    storageBucket: 'flutterfire-ui-codelab-851e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8SvAf67MC3v60GiMwmc6y1mrewIynRIw',
    appId: '1:1043694505574:ios:4be454464fabfe778627a7',
    messagingSenderId: '1043694505574',
    projectId: 'flutterfire-ui-codelab-851e7',
    storageBucket: 'flutterfire-ui-codelab-851e7.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8SvAf67MC3v60GiMwmc6y1mrewIynRIw',
    appId: '1:1043694505574:ios:fb4d610568b4456e8627a7',
    messagingSenderId: '1043694505574',
    projectId: 'flutterfire-ui-codelab-851e7',
    storageBucket: 'flutterfire-ui-codelab-851e7.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
